### ISSUE TITLE
IPAMObject has no attribute "dhcp_range"

### ISSUE THREAD

**Issue by impsik** [shadowychaos/phpipam-dhcp-config-generator#1]
I tested it without success. I run it like this:
`sudo python3 generate_dhcp_config.py -u admin -p password -e http://192.168.0.31:8080 -a ipam
`
When i run above command i get error:
`AttributeError: module 'datetime' has no attribute 'now'`
To solve that i added line:
`from datetime import datetime`

Second problem, when i ran above command ( I have DHCP range defined in phpipam):

```
Backing up original config.
Original config backed up.
Getting subnet DHCP data.
{'id': '141', 'subnet': '192.168.10.0', 'mask': '25', 'sectionId': '1', 'description': 'Imre testib', 'linked_subnet': None, 'firewallAddressObject': None, 'vrfId': '0', 'masterSubnetId': '0', 'allowRequests': '0', 'vlanId': '3', 'showName': '0', 'device': '0', 'permissions': [{'group_id': 3, 'permission': '1', 'name': 'Guests', 'desc': 'default Guest group (viewers)', 'members': False}, {'group_id': 2, 'permission': '2', 'name': 'Operators', 'desc': 'default Operator group', 'members': False}], 'pingSubnet': '0', 'discoverSubnet': '0', 'resolveDNS': '0', 'DNSrecursive': '0', 'DNSrecords': '0', 'nameserverId': '0', 'scanAgent': '0', 'customer_id': None, 'isFolder': '0', 'isFull': '0', 'tag': '2', 'threshold': '0', 'location': [], 'editDate': '2022-01-29 14:33:49', 'lastScan': None, 'lastDiscovery': None}
{'id': '141', 'subnet': '192.168.10.0', 'mask': '25', 'sectionId': '1', 'description': 'Imre testib', 'linked_subnet': None, 'firewallAddressObject': None, 'vrfId': '0', 'masterSubnetId': '0', 'allowRequests': '0', 'vlanId': '3', 'showName': '0', 'device': '0', 'permissions': [{'group_id': 3, 'permission': '1', 'name': 'Guests', 'desc': 'default Guest group (viewers)', 'members': False}, {'group_id': 2, 'permission': '2', 'name': 'Operators', 'desc': 'default Operator group', 'members': False}], 'pingSubnet': '0', 'discoverSubnet': '0', 'resolveDNS': '0', 'DNSrecursive': '0', 'DNSrecords': '0', 'nameserverId': '0', 'scanAgent': '0', 'customer_id': None, 'isFolder': '0', 'isFull': '0', 'tag': '2', 'threshold': '0', 'location': [], 'editDate': '2022-01-29 14:33:49', 'lastScan': None, 'lastDiscovery': None}
{'id': '141', 'subnet': '192.168.10.0', 'mask': '25', 'sectionId': '1', 'description': 'Imre testib', 'linked_subnet': None, 'firewallAddressObject': None, 'vrfId': '0', 'masterSubnetId': '0', 'allowRequests': '0', 'vlanId': '3', 'showName': '0', 'device': '0', 'permissions': [{'group_id': 3, 'permission': '1', 'name': 'Guests', 'desc': 'default Guest group (viewers)', 'members': False}, {'group_id': 2, 'permission': '2', 'name': 'Operators', 'desc': 'default Operator group', 'members': False}], 'pingSubnet': '0', 'discoverSubnet': '0', 'resolveDNS': '0', 'DNSrecursive': '0', 'DNSrecords': '0', 'nameserverId': '0', 'scanAgent': '0', 'customer_id': None, 'isFolder': '0', 'isFull': '0', 'tag': '2', 'threshold': '0', 'location': [], 'editDate': '2022-01-29 14:33:49', 'lastScan': None, 'lastDiscovery': None}
{'id': '141', 'subnet': '192.168.10.0', 'mask': '25', 'sectionId': '1', 'description': 'Imre testib', 'linked_subnet': None, 'firewallAddressObject': None, 'vrfId': '0', 'masterSubnetId': '0', 'allowRequests': '0', 'vlanId': '3', 'showName': '0', 'device': '0', 'permissions': [{'group_id': 3, 'permission': '1', 'name': 'Guests', 'desc': 'default Guest group (viewers)', 'members': False}, {'group_id': 2, 'permission': '2', 'name': 'Operators', 'desc': 'default Operator group', 'members': False}], 'pingSubnet': '0', 'discoverSubnet': '0', 'resolveDNS': '0', 'DNSrecursive': '0', 'DNSrecords': '0', 'nameserverId': '0', 'scanAgent': '0', 'customer_id': None, 'isFolder': '0', 'isFull': '0', 'tag': '2', 'threshold': '0', 'location': [], 'editDate': '2022-01-29 14:33:49', 'lastScan': None, 'lastDiscovery': None}
Traceback (most recent call last):
  File "generate_dhcp_config.py", line 136, in <module>
    print(main())
  File "generate_dhcp_config.py", line 128, in main
    result = run.create_config()
  File "generate_dhcp_config.py", line 96, in create_config
    config = self._dhcp_config_generator()
  File "generate_dhcp_config.py", line 53, in _dhcp_config_generator
    ranges = self._get_subnet_dhcp_ranges()
  File "generate_dhcp_config.py", line 44, in _get_subnet_dhcp_ranges
    dhcp_range = subnet_info.dhcp_range
  File "/home/imre/phpipam-dhcp-config-generator-main/classes.py", line 61, in __getattr__
    raise AttributeError(f'{__class__.__name__} has no attribute "{key}"')
AttributeError: IPAMObject has no attribute "dhcp_range"
```

**Comment by shadowychaos** [comment]
Thank you for the report! I've fixed the datetime usage issue. As for the dhcp_range issue, I see you're missing the custom static_percentage field in your IPAM config. This is required for calculations to determine how many of the IPs it should consider for the dhcp range. The error isn't descriptive much, so I've added some error checking to provide more information. Please try the solution on branch issue-1 to see if this resolves your issue.

**Comment by impsik** [comment]
datetime issue is resolved, thanks. But it's unclear where should i set this static_percentage field?
Is it custom field? I tried like this under Custom fields > Subnets:
![image](https://user-images.githubusercontent.com/22597757/151671492-6cc33dfa-92ee-4303-998e-47866c03ef59.png)
That gives me:
```
Traceback (most recent call last):
  File "generate_dhcp_config.py", line 141, in <module>
    print(main())
  File "generate_dhcp_config.py", line 133, in main
    result = run.create_config()
  File "generate_dhcp_config.py", line 101, in create_config
    config = self._dhcp_config_generator()
  File "generate_dhcp_config.py", line 58, in _dhcp_config_generator
    ranges = self._get_subnet_dhcp_ranges()
  File "generate_dhcp_config.py", line 45, in _get_subnet_dhcp_ranges
    dhcp_range = subnet_info.dhcp_range
  File "/home/imre/phpipam-dhcp-config-generator-main/classes.py", line 126, in dhcp_range
    static_integer = int(self.static_percentage)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by shadowychaos** [comment]
Yea, so by default, any new subnet fields don't apply to pre-existing subnets. So you'll need to go and set the static percentage for that subnet. Otherwise, it'll set it to null in the database, which will translate to a NoneType in Python.

**Comment by impsik** [comment]
OK, i deleted existing subnet created new subnet. As i understand vlan is mandatory, because i got:
`phpipam_client.client.PhpIpamException: {"code":404,"success":false,"message":"Vlan not found","time":0.006}`
That should be documented as well. Simple fix - create new vlan.
After adding vlan i got:
```
Traceback (most recent call last):
  File "generate_dhcp_config.py", line 141, in <module>
    print(main())
  File "generate_dhcp_config.py", line 133, in main
    result = run.create_config()
  File "generate_dhcp_config.py", line 116, in create_config
    raise DHCPDError(stderr)
classes.DHCPDError: b"systemctl: invalid option -- 'c'\n"
```
OS is centos 7.

**Comment by shadowychaos** [comment]
Thank you, documentation was updated in newest push to issue-1. Also fixed the systemctl command. Please give the new version a try and let me know how it goes. Please keep in mind this must be run on the DHCP server because it's expecting dhcpd installation and file paths. I've also added a requirements.txt to easily get all the dependencies needed.

**Comment by impsik** [comment]
It tries to restart dhcpd service but fails.
I have defined IP, hostname and Mac address. I ran the script and i got in /etc/dhcp/dhcpd.conf:
```
$ sudo cat /etc/dhcp/dhcpd.conf
#
# DHCP Server Configuration file.
#   see /usr/share/doc/dhcp-server/dhcpd.conf.example
#   see dhcpd.conf(5) man page
#

one-lease-per-client true;
log-facility local7;
ddns-update-style interim;

# Declare DHCP Server
authoritative;

# The default DHCP lease time
default-lease-time 7200;

# Set the maximum lease time
max-lease-time 7200;
```
